### ISSUE TITLE
Can edit code, but refresh/compile does nothing :-/

### ISSUE THREAD

**Issue by ghost** [Konloch/bytecode-viewer#125]
I have found the lines I want to edit, edited them, but when I hit refresh or compile, I see in cmd window that it is "allowing" execution of javac.exe, but that is all I see. When I look at BCV window it shows it is doing something forever. I check the appdata dir and I see temp files, but no changes in their filesizes or new files or files disappearing as you would expect if it is compiling things.

Originally tried from linux inside a windows vm but figured I would rule out the vm and try loading windows but still same problem.

This is exactly what I was looking to do, either manually or with an IDE. Decompile files in their place to java source, edit them, and recompile without loading into android studio (too much hassle for quick edits, never done it before) - I love you guys even though its not working :-/

Not sure what else to post here.

**Comment by MyS5Droid** [comment]
It looks like when I exit from BCV (go to cmd and ctrl+c) it shows a bunch of Java errors. So if I tried compiling same thing twice it shows the same errors twice.

My question to the Dev is: If you are going to silence the output of important things such as the compiler, and not even put in a message telling you it failed or succeeded, how are we to know what is happening? It doesn't even stop the cursor icon thing from going so you think it still doing something...

**Comment by Konloch** [comment]
Output isn't silenced, it's fed back into the frame upon fail (also should be spat out to console iirc).

Do you have any stack trace to send? If there was any exceptions throw it should open another window with a stack trace.

Also which decompiler were you using?

**Comment by MyS5Droid** [comment]
It just sat there "thinking" for more than 24 hours. It was doing absolutely
nothing. What I believe happened was the java compiler failed but the gui didn't
report anything. I believe this because when I close BCV in the console it all
of the sudden dumps the errors out.

Which frame are you referring to? One of the 3 code frames or the frames on the
left? Or it opens a new frame?

I can't remember I think I tried a few of the compilers in editable mode but I
think I liked the fernflower one most.

No exceptions thrown/stack trace unless that is what the java compiler errors
are from the console.

I still have found use for the program though, I like being able to see the
different decompile and compare them to smali code. I have been using dex2jar to
smali/backsmali.

I like the idea. The gui could be better but could also be worse and overall is
good. It's the functionality that matters for me, and for the most part I'd say
it's good for looking at code but I can't seem to compile :-/ Nice work though I
couldn't code that :P

On Wed, Feb 10, 2016 at 10:44 AM, Kalen (Konloch) Kinloch < notifications@github.com [notifications@github.com] > wrote:
Output isn't silenced, it's fed back into the frame upon fail (also should be
spat out to console iirc).

Do you have any stack trace to send? If there was any exceptions throw it should
open another window with a stack trace.

Also which decompiler were you using?

—
Reply to this email directly or view it on GitHub
[https://github.com/Konloch/bytecode-viewer/issues/125#issuecomment-182435520] .[https://github.com/notifications/beacon/APjUt-gmU2GnzSs_Gx1kSu3JlaW62rGLks5pi1JTgaJpZM4HV2Xg.gif]

**Comment by Konloch** [comment]
Whatever frame you're attempting to compile, if it fails compiling it will spit the errors into that frame.

And, I will need whatever got spat out of the console to debug this further.

Cheers!

**Comment by Konloch** [comment]
This should be fixed in v2.9.16, thanks for the report!
