### ISSUE TITLE
Add to home brew cask

### ISSUE THREAD

**Issue by jaredsburrows** [Konloch/bytecode-viewer#156]

**Comment by Aces-and-Jacks** [comment]
So this was canceled?

**Comment by Konloch** [comment]
Definitely open to this! I don't own a mac so I'm not familiar with homebrew cask. I would need to know the process we need to follow to publish. Are there any changes we would need to do to make the application compatible?

Possibly we could automate it using github actions or something similar, I think this would be a good addition either way.

**Comment by Aces-and-Jacks** [comment]
I'm glad that you'd be open to this...unfortunately I don't really do coding so I wouldn't know, despite this mainly being for people who mess around with java. Tho I would've helped if I knew how. 
 So I'm guessing this was mainly closed because you didn't know how to add to a home-brew cask and didn't want a stale issue being open.
