### ISSUE TITLE
bytecode-viewer releases are obfuscated!!

### ISSUE THREAD

**Issue by Lanchon** [Konloch/bytecode-viewer#26]
i hope this is a mistake. otherwise what would be the point of obfuscating a FLOSS tool?
i am trying to find the cause of a bug in bytecode-viewer but i can't because the release is obfuscated.

**Comment by cemo** [comment]
:)

**Comment by Konloch** [comment]
Not an issue, some libraries have namespace conflictions, so they needed to be obfuscated in order to work, mainly Dex2Jar uses ASM3 (needs to be obfuscated for ASM5 to work), and Smali/Baksmali have namespace issues (so one of them needs to be obfuscated for it to load both of them perfectly).

Let me know if you've got any more questions/concerns.

**Comment by Lanchon** [comment]
ohhhh... ok, thanks! i have never thought of obfuscation as solving this. you can use separate classloaders to load conflicting libraries simultaneously into a VM. class identity in the VM includes the classloader that loaded it.
