### ISSUE TITLE
Modifying byte code directly 

### ISSUE THREAD

**Issue by cemo** [Konloch/bytecode-viewer#32]
I would like to edit some byte code instructions without compiling file. Compiling a file requires a lot work to do. Is it possible to directly editing files instead of compiling? For example I would like to comment out some of instructions or change an operation code with some another. 

Thanks again for this tool @Konloch.

**Comment by Konloch** [comment]
Yes, select View Pane>Editable Pane 1 then View Pane>Pane 1>Krakatau Editable

Then open the classfile, do the changes you want, then do File>Compile.

That will 'compile (more like assemble)' the pseudo-bytecode to a proper classfile.


Glad you enjoyed it! If you've got any more questions feel free to reply to this. If you come across an issue/bug/suggestion make another ticket though.

**Comment by cemo** [comment]
I have set python executable and java rte library (I mean rt.jar ). Decompiling is working  fine. But compiling is not working. At least I can not see any output. 

1. What is the output folder for generated file?
2. An indicator about compiling would be nice. Opening a new issue?
3. Setting automatically python and jre runtime would be nice as well. User can overwrite in case a different environment. Opening a new issue?

**Comment by Konloch** [comment]
1) There is no output folder, if it compiles successfully it'll simply show a menu saying it's compiled successfully. Upon every press of 'Refresh' it should now load the latest code to all the panes instead of the one that's editable.
2) There is a menu that pops up saying you've compiled successfully or not, are you sure editable is enabled?
3) For me to do that I'd need all of the default install directories for python, pypy and the JRE/JDK, I suppose I could try automatic detection, but that'd be for 3.0 or 2.9.9.

Do you have Skype so we could screenshare and try to solve this issue 1:1? Cause there should be a menu that pops up alerting you on the compilation status.

Also, if you have Skype I could pass you beta 2.9.4 for some user input before I push it live! :D
