### ISSUE TITLE
Split View of bytecode viewer and Dcompiler is not working properly.

### ISSUE THREAD

**Issue by Geez14** [Konloch/bytecode-viewer#499]
Space allocation of the both bytecode viewer tab and Dcompiler is not working properly, when changing the widow size of the application using windows special functionalities of resizing window using "win+arrowkey" is not refreshing properly. 
Here is the video demo from the issue => [url](https://drive.google.com/file/d/1wmEcOWPjPMhCl5tF0uTYAZ2de0ILn23i/view?usp=sharing)

version of application : = 2.12

**Comment by Konloch** [comment]
Hi, this will be fixed in the latest BCV version, this should be fixed with https://github.com/Bl3nd/bytecode-viewer/commit/d441bb973b06cca407ae197c3ead0e226d572841

To test out the snapshot preview for this, you can view the latest built binary here - https://github.com/Konloch/bytecode-viewer/actions/runs/11136072303

If you encounter this issue with the latest version of BCV please open a new issue.
