### ISSUE TITLE
NullPointerException in Code Sequence Diagram plugin

### ISSUE THREAD

**Issue by Choonster** [Konloch/bytecode-viewer#53]
```
Bytecode Viewer Version: 2.9.5

java.lang.NullPointerException
	at the.bytecode.club.bytecodeviewer.plugins.CodeSequenceDiagram.execute(CodeSequenceDiagram.java:41)
	at the.bytecode.club.bytecodeviewer.api.Plugin.run(Plugin.java:26)
```
Let me know if you need any more information.

**Comment by Konloch** [comment]
Cheers, I'll take a look into this.

Could you provide the class that caused this?

**Comment by Choonster** [comment]
It seems to happen on every class I've tried, but specifically [this class](https://onedrive.live.com/redir?resid=5205E35027C028A!813&authkey=!ANUmA8-G-yCXxh0&ithint=file%2cclass) and every class I've tried in [this JAR](https://onedrive.live.com/redir?resid=5205E35027C028A!814&authkey=!AD6NvH66d_4gQFo&ithint=file%2cjar).

You can view the source of the JAR [here](https://github.com/Choonster/TestMod3/tree/87c2601d426ac9d6ae42695d2525e118cc3b99e7).

**Comment by Konloch** [comment]
Seems to be an issue with detecting the currently opened pane, not sure how this got introduced.

Will take a look a this further, thanks for the report!

**Comment by Konloch** [comment]
Fixed, really silly bug due to conflicting variables.

ClassViewer extends Viewer; Viewer has a ClassNode variable that's used and for some reason I created a ClassNode variable in ClassViewer under the same name, because of this it would bypass the Viewer variable and it would no longer get set.

So the solution was simply removing public ClassNode cn; from ClassViewer.

Cheers!
